# Generated by Django 4.1.2 on 2022-11-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='pregunta',
            field=models.IntegerField(null=True),
        ),
    ]
